# Generated by Django 5.2.7 on 2025-10-24 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL yang Dicek')),
                ('mode', models.CharField(choices=[('web', 'Web Browser'), ('whatsapp', 'WhatsApp Bot')], default='web', max_length=12)),
                ('message_content', models.TextField(blank=True, verbose_name='Isi Pesan Lengkap')),
                ('result_status', models.CharField(choices=[('safe', 'Aman'), ('suspicious', 'Mencurigakan'), ('dangerous', 'Berbahaya'), ('error', 'Error')], default='safe', max_length=20)),
                ('risk_score', models.IntegerField(default=0, verbose_name='Skor Risiko (0–100)')),
                ('sender_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address Pengirim')),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pengirim')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Riwayat Pengecekan',
                'verbose_name_plural': 'Riwayat Pengecekan',
                'ordering': ['-checked_at'],
            },
        ),
    ]
