# Generated by Django 5.2.7 on 2025-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Analisis'),
        ),
    ]
